	#elif CONFIG_CONSOLE_INDEX == 2
		/* FLEXCOM1 IOSET 1 USART pins */
		
	#elif CONFIG_CONSOLE_INDEX == 3
		/* FLEXCOM1 IOSET 2 USART pins */
		
	#elif CONFIG_CONSOLE_INDEX == 4
		/* FLEXCOM1 IOSET 3 USART pins */
		
	#elif CONFIG_CONSOLE_INDEX == 5
		/* FLEXCOM2 IOSET 1 USART pins */
		{"FLX_IO0", AT91C_PIN_PE(8), 0, PIO_DEFAULT, PIO_PERIPH_B},
		{"FLX_IO1", AT91C_PIN_PE(9), 0, PIO_DEFAULT, PIO_PERIPH_B},
	#elif CONFIG_CONSOLE_INDEX == 6
		/* FLEXCOM2 IOSET 2 USART pins */
		{"FLX_IO0", AT91C_PIN_PB(9), 0, PIO_DEFAULT, PIO_PERIPH_D},
		{"FLX_IO1", AT91C_PIN_PB(8), 0, PIO_DEFAULT, PIO_PERIPH_D},
	#elif CONFIG_CONSOLE_INDEX == 7
		/* FLEXCOM2 IOSET 3 USART pins */
		{"FLX_IO0", AT91C_PIN_PA(5), 0, PIO_DEFAULT, PIO_PERIPH_B},
		{"FLX_IO1", AT91C_PIN_PA(6), 0, PIO_DEFAULT, PIO_PERIPH_B},
	#elif CONFIG_CONSOLE_INDEX == 8
		/* FLEXCOM2 IOSET 4 USART pins */
		{"FLX_IO0", AT91C_PIN_PB(15), 0, PIO_DEFAULT, PIO_PERIPH_G},
		{"FLX_IO1", AT91C_PIN_PB(14), 0, PIO_DEFAULT, PIO_PERIPH_G},
	#elif CONFIG_CONSOLE_INDEX == 9
		/* FLEXCOM3 IOSET 1 USART pins */
		{"FLX_IO0", AT91C_PIN_PA(0), 0, PIO_DEFAULT, PIO_PERIPH_B},
		{"FLX_IO1", AT91C_PIN_PA(1), 0, PIO_DEFAULT, PIO_PERIPH_B},
	#elif CONFIG_CONSOLE_INDEX == 10
		/* FLEXCOM3 IOSET 2 USART pins */
		{"FLX_IO0", AT91C_PIN_PA(24), 0, PIO_DEFAULT, PIO_PERIPH_B},
		{"FLX_IO1", AT91C_PIN_PA(23), 0, PIO_DEFAULT, PIO_PERIPH_B},
	#elif CONFIG_CONSOLE_INDEX == 11
		/* FLEXCOM3 IOSET 3 USART pins */
		{"FLX_IO0", AT91C_PIN_PD(1), 0, PIO_DEFAULT, PIO_PERIPH_D},
		{"FLX_IO1", AT91C_PIN_PD(2), 0, PIO_DEFAULT, PIO_PERIPH_D},
	#elif CONFIG_CONSOLE_INDEX == 12
		/* FLEXCOM3 IOSET 4 USART pins */
		
	#elif CONFIG_CONSOLE_INDEX == 13
		/* FLEXCOM4 IOSET 1 USART pins */
		{"FLX_IO0", AT91C_PIN_PA(18), 0, PIO_DEFAULT, PIO_PERIPH_A},
		{"FLX_IO1", AT91C_PIN_PA(17), 0, PIO_DEFAULT, PIO_PERIPH_A},
	#elif CONFIG_CONSOLE_INDEX == 14
		/* FLEXCOM5 IOSET 1 USART pins */
		{"FLX_IO0", AT91C_PIN_PD(16), 0, PIO_DEFAULT, PIO_PERIPH_B},
		{"FLX_IO1", AT91C_PIN_PD(17), 0, PIO_DEFAULT, PIO_PERIPH_B},
	#elif CONFIG_CONSOLE_INDEX == 15
		/* FLEXCOM5 IOSET 2 USART pins */
		{"FLX_IO0", AT91C_PIN_PE(3), 0, PIO_DEFAULT, PIO_PERIPH_B},
		{"FLX_IO1", AT91C_PIN_PE(2), 0, PIO_DEFAULT, PIO_PERIPH_B},
	#elif CONFIG_CONSOLE_INDEX == 16
		/* FLEXCOM6 IOSET 1 USART pins */
		{"FLX_IO0", AT91C_PIN_PA(28), 0, PIO_DEFAULT, PIO_PERIPH_B},
		{"FLX_IO1", AT91C_PIN_PA(29), 0, PIO_DEFAULT, PIO_PERIPH_B},
	#elif CONFIG_CONSOLE_INDEX == 17
		/* FLEXCOM6 IOSET 2 USART pins */
		{"FLX_IO0", AT91C_PIN_PB(24), 0, PIO_DEFAULT, PIO_PERIPH_B},
		{"FLX_IO1", AT91C_PIN_PB(25), 0, PIO_DEFAULT, PIO_PERIPH_B},
	#elif CONFIG_CONSOLE_INDEX == 18
		/* FLEXCOM6 IOSET 3 USART pins */
		{"FLX_IO0", AT91C_PIN_PD(24), 0, PIO_DEFAULT, PIO_PERIPH_B},
		{"FLX_IO1", AT91C_PIN_PD(25), 0, PIO_DEFAULT, PIO_PERIPH_B},
	#elif CONFIG_CONSOLE_INDEX == 19
		/* FLEXCOM6 IOSET 4 USART pins */
		{"FLX_IO0", AT91C_PIN_PD(18), 0, PIO_DEFAULT, PIO_PERIPH_B},
		{"FLX_IO1", AT91C_PIN_PD(19), 0, PIO_DEFAULT, PIO_PERIPH_B},
	#elif CONFIG_CONSOLE_INDEX == 20
		/* FLEXCOM7 IOSET 1 USART pins */
		{"FLX_IO0", AT91C_PIN_PD(8), 0, PIO_DEFAULT, PIO_PERIPH_B},
		{"FLX_IO1", AT91C_PIN_PD(9), 0, PIO_DEFAULT, PIO_PERIPH_B},
	#elif CONFIG_CONSOLE_INDEX == 21
		/* FLEXCOM7 IOSET 2 USART pins */
		{"FLX_IO0", AT91C_PIN_PD(27), 0, PIO_DEFAULT, PIO_PERIPH_B},
		{"FLX_IO1", AT91C_PIN_PD(28), 0, PIO_DEFAULT, PIO_PERIPH_B},
	#elif CONFIG_CONSOLE_INDEX == 22
		/* FLEXCOM7 IOSET 3 USART pins */
		{"FLX_IO0", AT91C_PIN_PD(5), 0, PIO_DEFAULT, PIO_PERIPH_D},
		{"FLX_IO1", AT91C_PIN_PD(4), 0, PIO_DEFAULT, PIO_PERIPH_D},
	#elif CONFIG_CONSOLE_INDEX == 23
		/* FLEXCOM8 IOSET 1 USART pins */
		{"FLX_IO0", AT91C_PIN_PA(30), 0, PIO_DEFAULT, PIO_PERIPH_B},
		{"FLX_IO1", AT91C_PIN_PA(31), 0, PIO_DEFAULT, PIO_PERIPH_B},
	#elif CONFIG_CONSOLE_INDEX == 24
		/* FLEXCOM8 IOSET 2 USART pins */
		{"FLX_IO0", AT91C_PIN_PC(27), 0, PIO_DEFAULT, PIO_PERIPH_B},
		{"FLX_IO1", AT91C_PIN_PC(28), 0, PIO_DEFAULT, PIO_PERIPH_B},
	#elif CONFIG_CONSOLE_INDEX == 25
		/* FLEXCOM8 IOSET 3 USART pins */
		{"FLX_IO0", AT91C_PIN_PB(26), 0, PIO_DEFAULT, PIO_PERIPH_B},
		{"FLX_IO1", AT91C_PIN_PB(27), 0, PIO_DEFAULT, PIO_PERIPH_B},
	#elif CONFIG_CONSOLE_INDEX == 26
		/* FLEXCOM9 IOSET 1 USART pins */
		{"FLX_IO0", AT91C_PIN_PC(8), 0, PIO_DEFAULT, PIO_PERIPH_D},
		{"FLX_IO1", AT91C_PIN_PC(9), 0, PIO_DEFAULT, PIO_PERIPH_D},
	#elif CONFIG_CONSOLE_INDEX == 27
		/* FLEXCOM9 IOSET 2 USART pins */
		{"FLX_IO0", AT91C_PIN_PC(3), 0, PIO_DEFAULT, PIO_PERIPH_C},
		{"FLX_IO1", AT91C_PIN_PC(4), 0, PIO_DEFAULT, PIO_PERIPH_C},
	#elif CONFIG_CONSOLE_INDEX == 28
		/* FLEXCOM10 IOSET 1 USART pins */
		{"FLX_IO0", AT91C_PIN_PB(20), 0, PIO_DEFAULT, PIO_PERIPH_D},
		{"FLX_IO1", AT91C_PIN_PB(19), 0, PIO_DEFAULT, PIO_PERIPH_D},
	#elif CONFIG_CONSOLE_INDEX == 29
		/* FLEXCOM10 IOSET 2 USART pins */
		{"FLX_IO0", AT91C_PIN_PB(6), 0, PIO_DEFAULT, PIO_PERIPH_B},
		{"FLX_IO1", AT91C_PIN_PB(7), 0, PIO_DEFAULT, PIO_PERIPH_B},