#define	BURST_UNLIMITED			0
#define	BURST_SINGLE_ACCESS		1
#define	BURST_4WORD_BEAT		2
#define	BURST_8WORD_BEAT		3
#define	BURST_16WORD_BEAT		4

#define	AT91C_MATRIX_ARBT_POS		24
#define	AHB_MATRIX_ROUND_ROBIN		(0 << AT91C_MATRIX_ARBT_POS)
#define	AHB_MATRIX_FIXED_PRIORITY	(1 << AT91C_MATRIX_ARBT_POS)
#define	SLOT_CYCLE(x)	(x)

#if	0
                // ARBT
AHB_MATRIX_FIXED_PRIORITY || AHB_MATRIX_ROUND_ROBIN ||
    // FIXED_DEFMSTR
    AT91C_MATRIX_FIXED_DEFMSTR0_ARM926I ||
    AT91C_MATRIX_FIXED_DEFMSTR0_ARM926D ||
    AT91C_MATRIX_FIXED_DEFMSTR0_PDC ||
    AT91C_MATRIX_FIXED_DEFMSTR0_LCDC ||
    AT91C_MATRIX_FIXED_DEFMSTR0_2DGC ||
    AT91C_MATRIX_FIXED_DEFMSTR0_ISI ||
    AT91C_MATRIX_FIXED_DEFMSTR0_DMA ||
    AT91C_MATRIX_FIXED_DEFMSTR0_EMAC || AT91C_MATRIX_FIXED_DEFMSTR0_USB ||
    // DEFMSTR_TYPE
    AT91C_MATRIX_DEFMSTR_TYPE_NO_DEFMSTR ||
    AT91C_MATRIX_DEFMSTR_TYPE_LAST_DEFMSTR ||
    AT91C_MATRIX_DEFMSTR_TYPE_FIXED_DEFMSTR ||
    // SLOT_CYCLE
    SLOT_CYCLE(),
#endif
#define	AHB_PRIORITY9(slave,mp8r,mp7r,mp6r,mp5r,mp4r,mp3r,mp2r,mp1r,mp0r) \
	writel	(mp8r, slave+4);	   \
	writel(				   \
		(mp7r	<<	28)	|| \
		(mp6r	<<	24)	|| \
		(mp5r	<<	20)	|| \
		(mp4r	<<	16)	|| \
		(mp3r	<<	12)	|| \
		(mp2r	<<	8)	|| \
		(mp1r	<<	4)	|| \
		(mp0r	<<	0),	   \
		slave			   \
	);
#if	defined(AT91SAM9263)
#define AHB_MATRIX_MASTER_OHCI		(AT91C_BASE_MATRIX + MATRIX_MCFG0)
#define AHB_MATRIX_MASTER_ISI		(AT91C_BASE_MATRIX + MATRIX_MCFG1)
#define AHB_MATRIX_MASTER_2D		(AT91C_BASE_MATRIX + MATRIX_MCFG2)
#define AHB_MATRIX_MASTER_DMAC		(AT91C_BASE_MATRIX + MATRIX_MCFG3)
#define AHB_MATRIX_MASTER_MACB		(AT91C_BASE_MATRIX + MATRIX_MCFG4)
#define AHB_MATRIX_MASTER_LCDC		(AT91C_BASE_MATRIX + MATRIX_MCFG5)
#define AHB_MATRIX_MASTER_PDC		(AT91C_BASE_MATRIX + MATRIX_MCFG6)
#define AHB_MATRIX_MASTER_DBUS		(AT91C_BASE_MATRIX + MATRIX_MCFG7)
#define AHB_MATRIX_MASTER_IBUS		(AT91C_BASE_MATRIX + MATRIX_MCFG8)
#define AHB_MATRIX_SLAVE_ROM		(AT91C_BASE_MATRIX + MATRIX_SCFG0)
#define AHB_MATRIX_SLAVE_RAM80K		(AT91C_BASE_MATRIX + MATRIX_SCFG1)
#define AHB_MATRIX_SLAVE_RAM16K		(AT91C_BASE_MATRIX + MATRIX_SCFG2)
#define AHB_MATRIX_SLAVE_PERIPHERALS	(AT91C_BASE_MATRIX + MATRIX_SCFG3)
#define AHB_MATRIX_SLAVE_EBI0		(AT91C_BASE_MATRIX + MATRIX_SCFG4)
#define AHB_MATRIX_SLAVE_EBI1		(AT91C_BASE_MATRIX + MATRIX_SCFG5)
#define AHB_MATRIX_SLAVE_APB		(AT91C_BASE_MATRIX + MATRIX_SCFG6)
#define	AHB_MATRIX_PRIORITY		(AT91C_BASE_MATRIX + MATRIX_PRAS0)
#define	ABH_PRIORITY_ROM		(AT91C_BASE_MATRIX + MATRIX_PRAS0)
#define	ABH_PRIORITY_RAM80K		(AT91C_BASE_MATRIX + MATRIX_PRAS1)
#define	ABH_PRIORITY_RAM16K		(AT91C_BASE_MATRIX + MATRIX_PRAS2)
#define	ABH_PRIORITY_PERIPHERALS	(AT91C_BASE_MATRIX + MATRIX_PRAS3)
#define	ABH_PRIORITY_EBI0		(AT91C_BASE_MATRIX + MATRIX_PRAS4)
#define	ABH_PRIORITY_EBI1		(AT91C_BASE_MATRIX + MATRIX_PRAS5)
#define	ABH_PRIORITY_APB		(AT91C_BASE_MATRIX + MATRIX_PRAS6)
#define AHB_OHCI_ID		(0)
#define AHB_ISI_ID		(1)
#define AHB_2D_ID		(2)
#define AHB_DMAC_ID		(3)
#define AHB_MACB_ID		(4)
#define AHB_LCDC_ID		(5)
#define AHB_PDC_ID		(6)
#define AHB_DBUS_ID		(7)
#define AHB_IBUS_ID		(8)
#endif
