
#define NB_BANK_BITS	CONFIG_UMCTL2_NBANK
#define NB_ROW_BITS	CONFIG_UMCTL2_NR
#define NB_COL_BITS	CONFIG_UMCTL2_NC

#if defined(CONFIG_DDR2)
#define TRFC		CONFIG_UMCTL2_TRFC
#define TRRD		CONFIG_UMCTL2_TRRD
#define TWTR		CONFIG_UMCTL2_TWTR
#define TXP		CONFIG_UMCTL2_TXP
#define TXARD		CONFIG_UMCTL2_TXARD
#define TXARDS		CONFIG_UMCTL2_TXARDS
#define TFAW		CONFIG_UMCTL2_TFAW
#define TRP		CONFIG_UMCTL2_TRP
#define TRC		CONFIG_UMCTL2_TRC
#define CL		CONFIG_UMCTL2_CL
#define CWL		CONFIG_UMCTL2_CWL
#define RD_ODT_DELAY	CONFIG_UMCTL2_RD_ODT_DELAY
#define RD_ODT_HOLD	CONFIG_UMCTL2_RD_ODT_HOLD
#define WR_ODT_DELAY	CONFIG_UMCTL2_WR_ODT_DELAY
#define WR_ODT_HOLD	CONFIG_UMCTL2_WR_ODT_HOLD

#elif defined(CONFIG_DDR3)
#define TCKE		CONFIG_UMCTL2_TCKE
#define TRFC		CONFIG_UMCTL2_TRFC
#define TRRD		CONFIG_UMCTL2_TRRD
#define TFAW		CONFIG_UMCTL2_TFAW
#define TRP		CONFIG_UMCTL2_TRP
#define TRC		CONFIG_UMCTL2_TRC
#define TRASMIN		CONFIG_UMCTL2_TRASMIN
#define CL		CONFIG_UMCTL2_CL
#define CWL		CONFIG_UMCTL2_CWL

#elif defined(CONFIG_LPDDR2)
#define TREFI		CONFIG_UMCTL2_TREFI
#define TREFIpb		CONFIG_UMCTL2_TREFIPB
#define TRFCab		CONFIG_UMCTL2_TRFCAB
#define TRFCpb		CONFIG_UMCTL2_TRFCPB
#define TWTR		CONFIG_UMCTL2_TWTR
#define TDQSCK_MAX	CONFIG_UMCTL2_TDQSCK
#define TFAW		CONFIG_UMCTL2_TFAW
#define TCCD		CONFIG_UMCTL2_TCCD
#define RL		CONFIG_UMCTL2_RL
#define WL		CONFIG_UMCTL2_WL
#endif

#if defined(CONFIG_LPDDR3)
#define TREFI		CONFIG_UMCTL2_TREFI
#define TREFIpb		CONFIG_UMCTL2_TREFIPB
#define TRFCab		CONFIG_UMCTL2_TRFCAB
#define TRFCpb		CONFIG_UMCTL2_TRFCPB
#define RL		CONFIG_UMCTL2_RL
#define WL		CONFIG_UMCTL2_WL
#endif
