#!/bin/sh

usage() {
	echo "Usage: $0 [--save-scmversion] [srctree]" >&2
	exit 1
}

scm_only=false
srctree=.
if test "$1" = "--save-scmversion"; then
	scm_only=true
	shift
fi
if test $# -gt 0; then
	srctree=$1
	shift
fi
if test $# -gt 0 -o ! -d "$srctree"; then
	usage
fi

scm_version() {
	cd "$srctree" || exit 1

	if [ ! -d .git ]; then
		return
	fi

	# If at a tag, output nothing
	if git describe --exact-match --tags >/dev/null 2>&1; then
		return
	fi

	# Otherwise, output -<short_commit_sha>
	short_sha=$(git rev-parse --short HEAD 2>/dev/null)
	if [ -n "$short_sha" ]; then
		echo "-$short_sha"
	fi
}

if $scm_only; then
	if test ! -e .scmversion; then
		res=$(scm_version)
		echo "$res" >.scmversion
	fi
	exit
fi

res="$(scm_version)"
echo "$res"
